### ISSUE TITLE
Read trimming/filtering is not finding the necessary adapter file

### ISSUE THREAD

**Issue by holmrenser** [holmrenser/IOGA#4]
Continued from #3 

------

Hi Rens,

I have a problem! I'm using IOGA.py, but I keep seeing this error: OSError: [Errno 2]. Would you please help me solve this problem?
```
[teste] Quality trimming with BBduk

Traceback (most recent call last):

File "./IOGA.py", line 408, in main(args.reference,args.name,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)

File "./IOGA.py", line 352, in main

source,FP,RP,final_iteration = IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)

File "./IOGA.py", line 288, in IOGA_loop

forward,reverse = run_bbduk(name,forward,reverse,threads)

File "./IOGA.py", line 187, in run_bbduk subprocess.call(['bbduk.sh','ref='+adapterdir,'in='+forward,'in2='+reverse,'out='+FP,'out2='+RP,'threads='+threads,'k=25','ktrim=rl','qtrim=t','minlength=32','-Xmx10G'],stderr=fnull,stdout=fnull)

File "/usr/lib/python2.7/subprocess.py", line 522, in call

return Popen(popenargs, *kwargs).wait()

File "/usr/lib/python2.7/subprocess.py", line 710, in init

errread, errwrite)

File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child

raise child_exception

OSError: [Errno 2] No such file or directory
```
Best regards,

Lilian

**Comment by holmrenser** [comment]
As I mentioned in the title, this is problem with read trimming/filtering. I will try to upload a fix in the coming days. Stay tuned!

**Comment by Lilian-ufsc** [comment]
Hi Mr. Holmer,

Do you have any news about the script?
Best Regards!

Lilian

**Comment by holmrenser** [comment]
Hi Lilian,

I am currently merging several bug fixes and feature requests into a new release, this should be finished this week.

Let's hope it is worth the wait!

**Comment by Lilian-ufsc** [comment]
Thank you! I will wait.

Best regards,

Lilian

2015-09-21 10:57 GMT-03:00 holmrenser <notifications@github.com>:

> Hi Lilian,
>
> I am currently merging several bug fixes and feature requests into a new
> release, this should be finished this week.
>
> Let's hope it is worth the wait!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-141987952>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
This should be fixed now, so please pull the latest code.
After pulling, do the following:

* run ```python setup_IOGA.py``` in the same folder as IOGA.py
* this should generate a file: ``IOGA_config.json```

IOGA uses this file to find all the required dependencies, this should fix the problems you were having.

Please let me know if this works or does not work!

**Comment by Lilian-ufsc** [comment]
Dear Rens,

I've tried running the setup_IOGA.py code, but unfortunately it did not
work very well. It raises a problem when installing samtools. It seems that
the problem occurs when running the command *make* from the code.
I tired running it separately and it gives me the following message:













*make[1]: Entering directory
`/home/lilian/Documents/IOGA-master/exe/samtools-0.1.19'make[2]: Entering
directory `/home/lilian/Documents/IOGA-master/exe/samtools-0.1.19'gcc -c -g
-Wall -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE
-D_CURSES_LIB=1 -DBGZF_CACHE -I. bgzf.c -o bgzf.oIn file included from
bgzf.c:32:0:bgzf.h:33:18: fatal error: zlib.h: No such file or
directory #include <zlib.h>                  ^compilation
terminated.make[2]: *** [bgzf.o] Error 1make[2]: Leaving directory
`/home/lilian/Documents/IOGA-master/exe/samtools-0.1.19'make[1]: ***
[lib-recur] Error 1make[1]: Leaving directory
`/home/lilian/Documents/IOGA-master/exe/samtools-0.1.19'make: ***
[all-recur] Error 1*

I was wondering if it is possible to exclude the samtools downloading step
from the code, since I already have samtools installed in my computer.

Thanks for your help.

Best regards,

Lilian

2015-09-25 7:03 GMT-03:00 holmrenser <notifications@github.com>:

> This should be fixed now, so please pull the latest code.
> After pulling, do the following:
>
>    - run python setup_IOGA.py in the same folder as IOGA.py
>    - this should generate a file: IOGA_config.json`
>
> IOGA uses this file to find all the required dependencies, this should fix
> the problems you were having.
>
> Please let me know if this works or does not work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143178675>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
Hi Lillian, 
I am update the install script so that you will get a template of the config. You can then add the samtools path yourself.
In the meantime, it looks like your missing  zlib1g-dev. You could try installing that and see if it fixes the make error.

Cheers,

Rens

**Comment by Lilian-ufsc** [comment]
Hi Rens,

Installing the zlib1g-dev library did not solve the problem. I'll wait for
the new update then.

Thanks once again.

Best,

Lilian

2015-09-25 10:29 GMT-03:00 holmrenser <notifications@github.com>:

> Hi Lillian,
> I am update the install script so that you will get a template of the
> config. You can then add the samtools path yourself.
> In the meantime, it looks like your missing zlib1g-dev. You could try
> installing that and see if it fixes the make error.
>
> Cheers,
>
> Rens
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143223341>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
I pushed a fix, you can try that now.

**Comment by Lilian-ufsc** [comment]
Hi Rens,

I keep seeing this error:

/home/lilian/Documents/IOGA-master/IOGA_config.json
[teste] Quality trimming with BBduk
Iteration 1
[teste.1] BBmap
Traceback (most recent call last):
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 432, in <module>
    main(args.reference,args.name
,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 377, in main
    source,FP,RP,final_iteration =
IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 344, in IOGA_loop
    samfile = run_bbmap(folder,prefix,ref,forward,reverse,threads)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 113, in run_bbmap

subprocess.call([config['bbmap'],'ref='+ref,'in='+forward,'in2='+reverse,'threads='+threads,'outm='+mappedreads,'covstats='+covstats,'basecov='+basecov,'-Xmx10G','local=t','keepnames=t'],stdout=fnull,stderr=fnull)

KeyError: 'bbmap'

Regards,

Lilian


2015-09-25 10:38 GMT-03:00 holmrenser <notifications@github.com>:

> I pushed a fix, you can try that now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143226691>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
Could you post a copy of ```IOGA_config.json```?

**Comment by Lilian-ufsc** [comment]
Following a copy of IOGA_config.jso

{
 "picard.jar":
"/home/lilian/Documents/IOGA-master/exe/picard-tools-1.124/picard.jar",
 "samtools": "",
 "bbmap.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbmap.sh",
 "bbduk.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbduk.sh",
 "spades.py":
"/home/lilian/Documents/IOGA-master/exe/SPAdes-3.1.1-Linux/bin/spades.py",
 "ALE": "/home/lilian/Documents/IOGA-master/exe/ALE-master/src/ALE",
 "SOAPdenovo-127mer":
"/home/lilian/Documents/IOGA-master/exe/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-127mer",

 "adapters":
"/home/lilian/Documents/IOGA-master/exe/bbmap/alladapters.fa.gz",
 "seqtk": "/home/lilian/Documents/IOGA-master/exe/seqtk-master/seqtk"
}



2015-09-25 11:51 GMT-03:00 holmrenser <notifications@github.com>:

> Could you post a copy of IOGA_config.json?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143243724>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
Could you please check the fix?

On 25 Sep 2015, at 18:23, Lilian-ufsc <notifications@github.com<mailto:notifications@github.com>> wrote:

Following a copy of IOGA_config.jso

{
"picard.jar":
"/home/lilian/Documents/IOGA-master/exe/picard-tools-1.124/picard.jar",
"samtools": "",
"bbmap.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbmap.sh",
"bbduk.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbduk.sh",
"spades.py":
"/home/lilian/Documents/IOGA-master/exe/SPAdes-3.1.1-Linux/bin/spades.py",
"ALE": "/home/lilian/Documents/IOGA-master/exe/ALE-master/src/ALE",
"SOAPdenovo-127mer":
"/home/lilian/Documents/IOGA-master/exe/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-127mer",

"adapters":
"/home/lilian/Documents/IOGA-master/exe/bbmap/alladapters.fa.gz",
"seqtk": "/home/lilian/Documents/IOGA-master/exe/seqtk-master/seqtk"
}



2015-09-25 11:51 GMT-03:00 holmrenser <notifications@github.com<mailto:notifications@github.com>>:

> Could you post a copy of IOGA_config.json?
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143243724>.
>



--
Lilian de Oliveira Machado
Doutoranda em Recursos Gen?ticos Vegetais
Laborat?rio de Fisiologia do Desenvolvimento e Gen?tica Vegetal
UFSC/CCA
Fone(48)99767028

-

**Comment by Lilian-ufsc** [comment]
Following a new error:

/home/lilian/Documents/IOGA-master/IOGA_config.json
[guabiroba] Quality trimming with BBduk
Iteration 1
[guabiroba.1] BBmap
Traceback (most recent call last):
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 432, in <module>
    main(args.reference,args.name
,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 377, in main
    source,FP,RP,final_iteration =
IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 344, in IOGA_loop
    samfile = run_bbmap(folder,prefix,ref,forward,reverse,threads)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 114, in run_bbmap
    plot_coverage(basecov)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 121, in
plot_coverage
    with open(BBmap_coverage,'rU') as infile:
IOError: [Errno 2] No such file or directory:
'/home/lilian/Documents/IOGA-master/guabiroba.1/guabiroba.1.basecov.txt'



2015-09-25 13:26 GMT-03:00 holmrenser <notifications@github.com>:

> Could you please check the fix?
>
> On 25 Sep 2015, at 18:23, Lilian-ufsc <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> Following a copy of IOGA_config.jso
>
> {
> "picard.jar":
> "/home/lilian/Documents/IOGA-master/exe/picard-tools-1.124/picard.jar",
> "samtools": "",
> "bbmap.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbmap.sh",
> "bbduk.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbduk.sh",
> "spades.py":
> "/home/lilian/Documents/IOGA-master/exe/SPAdes-3.1.1-Linux/bin/spades.py",
> "ALE": "/home/lilian/Documents/IOGA-master/exe/ALE-master/src/ALE",
> "SOAPdenovo-127mer":
>
> "/home/lilian/Documents/IOGA-master/exe/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-127mer",
>
> "adapters":
> "/home/lilian/Documents/IOGA-master/exe/bbmap/alladapters.fa.gz",
> "seqtk": "/home/lilian/Documents/IOGA-master/exe/seqtk-master/seqtk"
> }
>
>
>
> 2015-09-25 11:51 GMT-03:00 holmrenser <notifications@github.com<mailto:
> notifications@github.com>>:
>
> > Could you post a copy of IOGA_config.json?
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143243724>.
> >
>
>
>
> --
> Lilian de Oliveira Machado
> Doutoranda em Recursos Gen?ticos Vegetais
> Laborat?rio de Fisiologia do Desenvolvimento e Gen?tica Vegetal
> UFSC/CCA
> Fone(48)99767028
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/holmrenser/IOGA/issues/4#issuecomment-143267678>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143268747>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
Are you able to run the bbmap.sh and bbduk.sh that were installed?

On 25 Sep 2015, at 18:54, Lilian-ufsc <notifications@github.com<mailto:notifications@github.com>> wrote:

Following a new error:

/home/lilian/Documents/IOGA-master/IOGA_config.json
[guabiroba] Quality trimming with BBduk
Iteration 1
[guabiroba.1] BBmap
Traceback (most recent call last):
File "/home/lilian/Documents/IOGA-master/IOGA.py", line 432, in <module>
main(args.reference,args.name
,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)
File "/home/lilian/Documents/IOGA-master/IOGA.py", line 377, in main
source,FP,RP,final_iteration =
IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
File "/home/lilian/Documents/IOGA-master/IOGA.py", line 344, in IOGA_loop
samfile = run_bbmap(folder,prefix,ref,forward,reverse,threads)
File "/home/lilian/Documents/IOGA-master/IOGA.py", line 114, in run_bbmap
plot_coverage(basecov)
File "/home/lilian/Documents/IOGA-master/IOGA.py", line 121, in
plot_coverage
with open(BBmap_coverage,'rU') as infile:
IOError: [Errno 2] No such file or directory:
'/home/lilian/Documents/IOGA-master/guabiroba.1/guabiroba.1.basecov.txt'



2015-09-25 13:26 GMT-03:00 holmrenser <notifications@github.com<mailto:notifications@github.com>>:

> Could you please check the fix?
>
> On 25 Sep 2015, at 18:23, Lilian-ufsc <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>> wrote:
>
> Following a copy of IOGA_config.jso
>
> {
> "picard.jar":
> "/home/lilian/Documents/IOGA-master/exe/picard-tools-1.124/picard.jar",
> "samtools": "",
> "bbmap.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbmap.sh",
> "bbduk.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbduk.sh",
> "spades.py":
> "/home/lilian/Documents/IOGA-master/exe/SPAdes-3.1.1-Linux/bin/spades.py",
> "ALE": "/home/lilian/Documents/IOGA-master/exe/ALE-master/src/ALE",
> "SOAPdenovo-127mer":
>
> "/home/lilian/Documents/IOGA-master/exe/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-127mer",
>
> "adapters":
> "/home/lilian/Documents/IOGA-master/exe/bbmap/alladapters.fa.gz",
> "seqtk": "/home/lilian/Documents/IOGA-master/exe/seqtk-master/seqtk"
> }
>
>
>
> 2015-09-25 11:51 GMT-03:00 holmrenser <notifications@github.com<mailto:notifications@github.com><mailto:
> notifications@github.com<mailto:notifications@github.com>>>:
>
> > Could you post a copy of IOGA_config.json?
> >
> > -
> > Reply to this email directly or view it on GitHub
> > <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143243724>.
> >
>
>
>
> --
> Lilian de Oliveira Machado
> Doutoranda em Recursos Gen?ticos Vegetais
> Laborat?rio de Fisiologia do Desenvolvimento e Gen?tica Vegetal
> UFSC/CCA
> Fone(48)99767028
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/holmrenser/IOGA/issues/4#issuecomment-143267678>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143268747>.
>



--
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by Lilian-ufsc** [comment]
Yes, both were installed.

2015-09-25 15:07 GMT-03:00 holmrenser <notifications@github.com>:

> Are you able to run the bbmap.sh and bbduk.sh that were installed?
>
> On 25 Sep 2015, at 18:54, Lilian-ufsc <notifications@github.com<mailto:
> notifications@github.com>> wrote:
>
> Following a new error:
>
> /home/lilian/Documents/IOGA-master/IOGA_config.json
> [guabiroba] Quality trimming with BBduk
> Iteration 1
> [guabiroba.1] BBmap
> Traceback (most recent call last):
> File "/home/lilian/Documents/IOGA-master/IOGA.py", line 432, in <module>
> main(args.reference,args.name
> ,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)
>
> File "/home/lilian/Documents/IOGA-master/IOGA.py", line 377, in main
> source,FP,RP,final_iteration =
> IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
> File "/home/lilian/Documents/IOGA-master/IOGA.py", line 344, in IOGA_loop
> samfile = run_bbmap(folder,prefix,ref,forward,reverse,threads)
> File "/home/lilian/Documents/IOGA-master/IOGA.py", line 114, in run_bbmap
> plot_coverage(basecov)
> File "/home/lilian/Documents/IOGA-master/IOGA.py", line 121, in
> plot_coverage
> with open(BBmap_coverage,'rU') as infile:
> IOError: [Errno 2] No such file or directory:
> '/home/lilian/Documents/IOGA-master/guabiroba.1/guabiroba.1.basecov.txt'
>
>
>
> 2015-09-25 13:26 GMT-03:00 holmrenser <notifications@github.com<mailto:
> notifications@github.com>>:
>
> > Could you please check the fix?
> >
> > On 25 Sep 2015, at 18:23, Lilian-ufsc <notifications@github.com<mailto:
> notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>>> wrote:
> >
> > Following a copy of IOGA_config.jso
> >
> > {
> > "picard.jar":
> > "/home/lilian/Documents/IOGA-master/exe/picard-tools-1.124/picard.jar",
> > "samtools": "",
> > "bbmap.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbmap.sh",
> > "bbduk.sh": "/home/lilian/Documents/IOGA-master/exe/bbmap/bbduk.sh",
> > "spades.py":
> >
> "/home/lilian/Documents/IOGA-master/exe/SPAdes-3.1.1-Linux/bin/spades.py",
> > "ALE": "/home/lilian/Documents/IOGA-master/exe/ALE-master/src/ALE",
> > "SOAPdenovo-127mer":
> >
> >
> "/home/lilian/Documents/IOGA-master/exe/SOAPdenovo2-bin-LINUX-generic-r240/SOAPdenovo-127mer",
>
> >
> > "adapters":
> > "/home/lilian/Documents/IOGA-master/exe/bbmap/alladapters.fa.gz",
> > "seqtk": "/home/lilian/Documents/IOGA-master/exe/seqtk-master/seqtk"
> > }
> >
> >
> >
> > 2015-09-25 11:51 GMT-03:00 holmrenser <notifications@github.com<mailto:
> notifications@github.com><mailto:
> > notifications@github.com<mailto:notifications@github.com>>>:
> >
> > > Could you post a copy of IOGA_config.json?
> > >
> > > -
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143243724>.
> > >
> >
> >
> >
> > --
> > Lilian de Oliveira Machado
> > Doutoranda em Recursos Gen?ticos Vegetais
> > Laborat?rio de Fisiologia do Desenvolvimento e Gen?tica Vegetal
> > UFSC/CCA
> > Fone(48)99767028
> >
> > -
> > Reply to this email directly or view it on GitHub<
> > https://github.com/holmrenser/IOGA/issues/4#issuecomment-143267678>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143268747>.
> >
>
>
>
> --
> Lilian de Oliveira Machado
> Doutoranda em Recursos Genéticos Vegetais
> Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
> UFSC/CCA
> Fone(48)99767028
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/holmrenser/IOGA/issues/4#issuecomment-143279175>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143310279>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
Can you tell me what files are in the folder ```guabiroba.1```, and what the exact command is that you used?

**Comment by Lilian-ufsc** [comment]
Sure!

Just one file.The file in the folder guabi.1 is guabi.1.temp.fasta.

Commands:

root@bioinfo-Precision-Tower-5810:/home/lilian/Documents/IOGA-master#
IOGA.py -n guabi -r chloroplast.reference.fasta -1
CampomanesiaXanthocarpa_S6_L001_R1_001.fastq -2
CampomanesiaXanthocarpa_S6_L001_R2 -i 300 -t 8
/home/lilian/Documents/IOGA-master/IOGA_config.json
/home/lilian/Documents/IOGA-master/IOGA_config.json
[guabi] Quality trimming with BBduk
Folder /home/lilian/Documents/IOGA-master/guabi.1 exists, overwriting
Iteration 1
[guabi.1] BBmap
Traceback (most recent call last):
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 432, in <module>
    main(args.reference,args.name
,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 377, in main
    source,FP,RP,final_iteration =
IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 344, in IOGA_loop
    samfile = run_bbmap(folder,prefix,ref,forward,reverse,threads)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 114, in run_bbmap
    plot_coverage(basecov)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 121, in
plot_coverage
    with open(BBmap_coverage,'rU') as infile:
IOError: [Errno 2] No such file or directory:
'/home/lilian/Documents/IOGA-master/guabi.1/guabi.1.basecov.txt'
root@bioinfo-Precision-Tower-5810:/home/lilian/Documents/IOGA-master#

2015-09-25 15:19 GMT-03:00 holmrenser <notifications@github.com>:

> Can you tell me what files are in the folder guabiroba.1, and what the
> exact command is that you used?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143313186>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
I suspect the problem is in your IOGA.py command.

You typed: ```IOGA.py -n guabi -r chloroplast.reference.fasta -1 CampomanesiaXanthocarpa_S6_L001_R1_001.fastq -2 CampomanesiaXanthocarpa_S6_L001_R2 -i 300 -t 8```.

The second readfile probably should be ```CampomanesiaXanthocarpa_S6_L001_R2_001.fastq``` ?

**Comment by Lilian-ufsc** [comment]
Unfortunately not, I fixed the comand but I still get the same error.


root@bioinfo-Precision-Tower-5810:/home/lilian/Documents/IOGA-master#
IOGA.py -n guabi -r chloroplast.reference.fasta -1
CampomanesiaXanthocarpa_S6_L001_R1_001.fastq -2
CampomanesiaXanthocarpa_S6_L001_R2_001.fastq -i 300 -t 8
/home/lilian/Documents/IOGA-master/IOGA_config.json
/home/lilian/Documents/IOGA-master/IOGA_config.json
[guabi] Quality trimming with BBduk
Folder /home/lilian/Documents/IOGA-master/guabi.1 exists, overwriting
Iteration 1
[guabi.1] BBmap
Traceback (most recent call last):
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 432, in <module>
    main(args.reference,args.name
,args.forward,args.reverse,args.threads,args.insertsize,args.maxrounds,args.verbose)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 377, in main
    source,FP,RP,final_iteration =
IOGA_loop(name,ref,forward,reverse,insertsize,threads,maxrounds)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 344, in IOGA_loop
    samfile = run_bbmap(folder,prefix,ref,forward,reverse,threads)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 114, in run_bbmap
    plot_coverage(basecov)
  File "/home/lilian/Documents/IOGA-master/IOGA.py", line 121, in
plot_coverage
    with open(BBmap_coverage,'rU') as infile:
IOError: [Errno 2] No such file or directory:
'/home/lilian/Documents/IOGA-master/guabi.1/guabi.1.basecov.txt'

2015-09-25 15:37 GMT-03:00 holmrenser <notifications@github.com>:

> I suspect the problem is in your IOGA.py command.
>
> You typed: IOGA.py -n guabi -r chloroplast.reference.fasta -1
> CampomanesiaXanthocarpa_S6_L001_R1_001.fastq -2
> CampomanesiaXanthocarpa_S6_L001_R2 -i 300 -t 8.
>
> The second readfile probably should be
> CampomanesiaXanthocarpa_S6_L001_R2_001.fastq ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-143317442>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
Do you still have these issues?

So far I have been unable to reproduce these errors. Do you have java7?

For sure I will work on more informative logging and error messages.

**Comment by holmrenser** [comment]
Also I fixed an error with the adapters. 
I think it should work now...

**Comment by Lilian-ufsc** [comment]
Hi Rens,

I installed java 7 but it's not working. So, I installed java 8 and I
trying to run.
Typical runtime on 4 threads is ~20minutes, but I used 2 threads and it's
taking sometime. Is it right?

Regards

Lilian

2015-10-08 12:04 GMT-03:00 holmrenser <notifications@github.com>:

> Also I fixed an error with the adapters.
> I think it should work now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-146573096>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by Lilian-ufsc** [comment]
Java error - threads error

Here are thread error messages:

lilian@bioinfo-Precision-Tower-5810:~/Downloads/IOGA-master$ ./IOGA.py -r
chloroplast.reference.fasta -n teste -1
/home/lilian/Documents/Guabiroba/CampomanesiaXanthocarpa_S6_L001_R1_001.fastq
-2
/home/lilian/Documents/Guabiroba/CampomanesiaXanthocarpa_S6_L001_R2_001.fastq
-i 300 -t 4 -v
/home/lilian/Downloads/IOGA-master/IOGA_config.json
/home/lilian/Downloads/IOGA-master/IOGA_config.json
[teste] Quality trimming with BBduk
java -ea -Xmx10G -cp /home/lilian/Downloads/IOGA-master/exe/bbmap/current/
jgi.BBDukF
ref=/home/lilian/Downloads/IOGA-master/exe/bbmap/alladapters.fa.gz
in=/home/lilian/Documents/Guabiroba/CampomanesiaXanthocarpa_S6_L001_R1_001.fastq
in2=/home/lilian/Documents/Guabiroba/CampomanesiaXanthocarpa_S6_L001_R2_001.fastq
out=teste.temp.filtered.R1.fastq out2=teste.temp.filtered.R2.fastq
threads=4 k=25 ktrim=rl qtrim=t minlength=32 -Xmx10G
Executing jgi.BBDukF
[ref=/home/lilian/Downloads/IOGA-master/exe/bbmap/alladapters.fa.gz,
in=/home/lilian/Documents/Guabiroba/CampomanesiaXanthocarpa_S6_L001_R1_001.fastq,
in2=/home/lilian/Documents/Guabiroba/CampomanesiaXanthocarpa_S6_L001_R2_001.fastq,
out=teste.temp.filtered.R1.fastq, out2=teste.temp.filtered.R2.fastq,
threads=4, k=25, ktrim=rl, qtrim=t, minlength=32, -Xmx10G]

Initial:
Memory: free=486m, used=18m

Exception in thread "Thread-8" java.lang.AssertionError: 0, 238296, 2
    at stream.FastaReadInputStream.nextHeader(FastaReadInputStream.java:317)
    at stream.FastaReadInputStream.fillList(FastaReadInputStream.java:205)
    at stream.FastaReadInputStream.hasMore(FastaReadInputStream.java:137)
    at
stream.ConcurrentGenericReadInputStream$ReadThread.readLists(ConcurrentGenericReadInputStream.java:746)
    at
stream.ConcurrentGenericReadInputStream$ReadThread.run(ConcurrentGenericReadInputStream.java:738)


Would you help me, please?
Thank you!

2015-10-09 14:50 GMT-03:00 Lilian Machado <lilian.o.machado@gmail.com>:

> Hi Rens,
>
> I installed java 7 but it's not working. So, I installed java 8 and I
> trying to run.
> Typical runtime on 4 threads is ~20minutes, but I used 2 threads and it's
> taking sometime. Is it right?
>
> Regards
>
> Lilian
>
> 2015-10-08 12:04 GMT-03:00 holmrenser <notifications@github.com>:
>
>> Also I fixed an error with the adapters.
>> I think it should work now...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-146573096>.
>>
>
>
>
> --
> Lilian de Oliveira Machado
> Doutoranda em Recursos Genéticos Vegetais
> Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
> UFSC/CCA
> Fone(48)99767028
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
This is proving to be an excellent test case! Thanks for sticking with me. I think your latest error is a result of a bug in the adapter sequences for read trimming. This should be fixed now, so please make sure you do a ```git pull``` and check again.

If that doesn't fix things, please check in again!

**Comment by Lilian-ufsc** [comment]
Have you update the script on the github page? I haven't found any new
files there, today.

Cheers.

2015-10-09 16:01 GMT-03:00 holmrenser <notifications@github.com>:

> This is proving to be an excellent test case! Thanks for sticking with me.
> I think your latest error is a result of a bug in the adapter sequences for
> read trimming. This should be fixed now, so please make sure you do a git
> pull and check again.
>
> If that doesn't fix things, please check in again!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-146961859>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
No new files, but they have changed ;-)

**Comment by Lilian-ufsc** [comment]
Dear Rens,

Great sucess, problem solved!

Thank you so much :)

Cheers,

Lilian



2015-10-10 6:17 GMT-03:00 holmrenser <notifications@github.com>:

> No new files, but they have changed ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holmrenser/IOGA/issues/4#issuecomment-147068003>.
>



-- 
Lilian de Oliveira Machado
Doutoranda em Recursos Genéticos Vegetais
Laboratório de Fisiologia do Desenvolvimento e Genética Vegetal
UFSC/CCA
Fone(48)99767028

**Comment by holmrenser** [comment]
Hurray! Thank you a lot for working this out with me!
